### ISSUE TITLE
Exception “The distance must be greater than zero!” when providing same coords twice 

### ISSUE THREAD

**Issue by alexisLefebvre** [bobsta63/distical#3]
Hello and thanks for the library.

I get an error when I try to calculate the distance between 2 points that have same coordinates.

I think it should check with `!$distance >= 0` instead of `!$distance > 0` here:

https://github.com/allebb/distical/blob/892f9a172307bf5148f476da2a856de20a54eac0/src/Entities/Distance.php#L57-L59

A distance of `0` is valid in my humble opinion.

One (untested) example:

```php
$centralIpswich = new LatLong(51.73441738801072, 0.4632282257080078); // Central Ipswich co-ordinates!
$centralAylesbury = new LatLong(51.73441738801072, 0.4632282257080078); // Central Ipswich co-ordinates!

// Create a new instance of the class passing in two coordinates (LatLong objects)
$pointToPointCalculator = new Calculator($centralIpswich, $centralAylesbury);

// Calculate the distance and return in both kilometre and miles...
$km = $pointToPointCalculator->get()->asKilometres();
```

**Comment by allebb** [comment]
This has now been implement in PR: https://github.com/allebb/distical/pull/4
